### ISSUE TITLE
Nuget seems to be missing fixes for #15

### ISSUE THREAD

**Issue by skether** [jordanlytle/SmbAbstraction#18]
This is a follow up for #15.
I updated the nuget version to 1.0.11 and later 1.1.0 and the problem persists.
I cloned the repo and tested directly in the solution there and the fix works as expected, (I was able to reproduce the issue by rolling back to 975e9e4454b7ef65d4019b52933f63b7c522f1e4).
It seems to me that the nugets were built from an older commit.

Thanks in advance!

**Comment by Jo0** [comment]
Terribly sorry about that. I just published version 1.1.1, which I ensured was off of a fresh build, and pulled it down locally. Re-tested with your snippet from issue #15, looks like things are good now.

**Comment by skether** [comment]
I tested version 1.1.1 and the fix works as expected.
Thank you!
