### ISSUE TITLE
SMBCredential's domain argument, when null, results in unhandled null reference exception

### ISSUE THREAD

**Issue by Coderrob** [jordanlytle/SmbAbstraction#5]
Leaving the domain value null on `SMBCredential` will result in a null reference exception thrown when attempting to run `Connect()`:

```
        private void Connect()
        {
            var succeded = SMBClient.Connect(_address, _transport);
            if(!succeded)
            {
                throw new IOException($"Unable to connect to SMB share.");
            }
            var status = SMBClient.Login(_credential.Domain, _credential.UserName, _credential.Password);
            status.HandleStatus();
        }
```

Likely need to include some guard classes to assert that values are not null to throw argument exceptions.

**Comment by jordanlytle** [comment]
Thanks for finding this issue Rob, I should have a fix for this sometime this week

**Comment by jordanlytle** [comment]
This has been addressed in the latest version of the nuget package (1.0.5)
